Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: alex-CF-task-vpc1
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: alex-vpc1-igw1

  InternetGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    DependsOn: VPC
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  SUBNETSTACK:
    DependsOn: InternetGatewayAttachment
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-1j19vo3uv948v-us-east-1.s3.amazonaws.com/subnets-nested-stack.yaml
      Parameters:
        VpcIdParam: !Ref VPC
        IgwIdParam: !Ref InternetGateway