Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: alex-CF-task-vpc1
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: alex-vpc1-igw1
  InternetGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
      DependsOn: VPC

  SUBNETSTACK:
    Type: AWS::CloudFormarion::Stack
    Properties:
    TemplateURL: https://raw.githubusercontent.com/Alex-SBK/alexcloudformation/master/subnets-nested-stack.yaml
    Paremeters:
      VpcIdParam: !Ref VPC


