Resources:
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PublicCIDR
      VpcId: !Ref VpcIdParam
      AvailabilityZone: !Select [ !Ref AZnumber, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: publicSubnet
  DBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref DBCIDR
      VpcId: !Ref VpcIdParam
      AvailabilityZone: !Select [ !Ref AZnumber, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: DBSubnet

  # Public RT
  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcIdParam
      Tags:
        - Key: Name
          Value: rt-public
  RouteTablePublicDefaultIPv4:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: RouteTablePublic
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref IgwIdParam
  SubnetRouteTableAssociationPublicSn:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTablePublic
      SubnetId: !Ref PublicSubnet

Parameters:
  VpcIdParam:
    Description: ID of VPC
    Type: String
  IgwIdParam:
    Description: ID of Gateway
    Type: String
  PublicCIDR:
    Description: CIDR for public Subnet
    Type: String
  DBCIDR:
    Description: CIDR for DB Subnet
    Type: String
  AZnumber:
    Description: Number of AZ
    Type: String

